import { Injectable } from "@nestjs/common";

@Injectable()
export default class AppActions {

    /**
     * USER PERMIT
     */
    public readonly APP_PERMIT_USER_LIST = `APP_PERMIT_USER_LIST`;
    public readonly APP_PERMIT_USER_CREATE = `APP_PERMIT_USER_CREATE`;
    public readonly APP_PERMIT_USER_UPDATE = `APP_PERMIT_USER_UPDATE`;
    public readonly APP_PERMIT_USER_DELETE = `APP_PERMIT_USER_DELETE`;
    public readonly APP_PERMIT_USER_RECOVERY = `APP_PERMIT_USER_RECOVERY`;
    public readonly APP_PERMIT_USER_COUNT = `APP_PERMIT_USER_COUNT`;
    public readonly APP_PERMIT_USER_SPECITY_ADMIN_APP = `APP_PERMIT_USER_SPECITY_ADMIN_APP`;
    public readonly APP_PERMIT_USER_SPECITY_NUTRI_APP = `APP_PERMIT_USER_SPECITY_NUTRI_APP`;
    public readonly APP_PERMIT_USER_SPECITY_FINANCE = `APP_PERMIT_USER_SPECITY_FINANCE`;
    public readonly APP_PERMIT_USER_SPECITY_NUTRICIONISTA = `APP_PERMIT_USER_SPECITY_NUTRICIONISTA`;
    public readonly APP_PERMIT_USER_SPECITY_PACIENTE = `APP_PERMIT_USER_SPECITY_PACIENTE`;

    /**
         * USER PERMIT
         */
    public readonly APP_PERMIT_HISTORY_LIST = `APP_PERMIT_HISTORY_LIST`;
    public readonly APP_PERMIT_HISTORY_CREATE = `APP_PERMIT_HISTORY_CREATE`;
    public readonly APP_PERMIT_HISTORY_UPDATE = `APP_PERMIT_HISTORY_UPDATE`;
    public readonly APP_PERMIT_HISTORY_DELETE = `APP_PERMIT_HISTORY_DELETE`;
    public readonly APP_PERMIT_HISTORY_RECOVERY = `APP_PERMIT_HISTORY_RECOVERY`;
    public readonly APP_PERMIT_HISTORY_COUNT = `APP_PERMIT_HISTORY_COUNT`;

    /**
     * PERMIT PERMIT
     */
    public readonly APP_PERMIT_PERMIT_LIST = `APP_PERMIT_PERMIT_LIST`;
    public readonly APP_PERMIT_PERMIT_CREATE = `APP_PERMIT_PERMIT_CREATE`;
    public readonly APP_PERMIT_PERMIT_UPDATE = `APP_PERMIT_PERMIT_UPDATE`;
    public readonly APP_PERMIT_PERMIT_DELETE = `APP_PERMIT_PERMIT_DELETE`;
    public readonly APP_PERMIT_PERMIT_RECOVERY = `APP_PERMIT_PERMIT_RECOVERY`;
    public readonly APP_PERMIT_PERMIT_COUNT = `APP_PERMIT_PERMIT_COUNT`;



    /**
     * COUNTRY PERMIT
     */
    public readonly APP_PERMIT_COUNTRY_LIST = `APP_PERMIT_COUNTRY_LIST`;
    public readonly APP_PERMIT_COUNTRY_CREATE = `APP_PERMIT_COUNTRY_CREATE`;
    public readonly APP_PERMIT_COUNTRY_UPDATE = `APP_PERMIT_COUNTRY_UPDATE`;
    public readonly APP_PERMIT_COUNTRY_DELETE = `APP_PERMIT_COUNTRY_DELETE`;
    public readonly APP_PERMIT_COUNTRY_RECOVERY = `APP_PERMIT_COUNTRY_RECOVERY`;
    public readonly APP_PERMIT_COUNTRY_COUNT = `APP_PERMIT_COUNTRY_COUNT`;



    /**
     * NOTIFICATION PERMIT
     */
    public readonly APP_PERMIT_NOTIFICATION_LIST = `APP_PERMIT_NOTIFICATION_LIST`;
    public readonly APP_PERMIT_NOTIFICATION_CREATE = `APP_PERMIT_NOTIFICATION_CREATE`;
    public readonly APP_PERMIT_NOTIFICATION_UPDATE = `APP_PERMIT_NOTIFICATION_UPDATE`;
    public readonly APP_PERMIT_NOTIFICATION_DELETE = `APP_PERMIT_NOTIFICATION_DELETE`;
    public readonly APP_PERMIT_NOTIFICATION_RECOVERY = `APP_PERMIT_NOTIFICATION_RECOVERY`;
    public readonly APP_PERMIT_NOTIFICATION_COUNT = `APP_PERMIT_NOTIFICATION_COUNT`;


    /**
     * STATE PERMIT
     */
    public readonly APP_PERMIT_STATE_LIST = `APP_PERMIT_STATE_LIST`;
    public readonly APP_PERMIT_STATE_CREATE = `APP_PERMIT_STATE_CREATE`;
    public readonly APP_PERMIT_STATE_UPDATE = `APP_PERMIT_STATE_UPDATE`;
    public readonly APP_PERMIT_STATE_DELETE = `APP_PERMIT_STATE_DELETE`;
    public readonly APP_PERMIT_STATE_RECOVERY = `APP_PERMIT_STATE_RECOVERY`;
    public readonly APP_PERMIT_STATE_COUNT = `APP_PERMIT_STATE_COUNT`;

    /**
     * CITY PERMIT
     */
    public readonly APP_PERMIT_CITY_LIST = `APP_PERMIT_CITY_LIST`;
    public readonly APP_PERMIT_CITY_CREATE = `APP_PERMIT_CITY_CREATE`;
    public readonly APP_PERMIT_CITY_UPDATE = `APP_PERMIT_CITY_UPDATE`;
    public readonly APP_PERMIT_CITY_DELETE = `APP_PERMIT_CITY_DELETE`;
    public readonly APP_PERMIT_CITY_RECOVERY = `APP_PERMIT_CITY_RECOVERY`;
    public readonly APP_PERMIT_CITY_COUNT = `APP_PERMIT_CITY_COUNT`;

    /**
     * SUBSCRIPTION PERMIT
     */
    public readonly APP_PERMIT_SUBSCRIPTION_LIST = `APP_PERMIT_SUBSCRIPTION_LIST`;
    public readonly APP_PERMIT_SUBSCRIPTION_CREATE = `APP_PERMIT_SUBSCRIPTION_CREATE`;
    public readonly APP_PERMIT_SUBSCRIPTION_UPDATE = `APP_PERMIT_SUBSCRIPTION_UPDATE`;
    public readonly APP_PERMIT_SUBSCRIPTION_DELETE = `APP_PERMIT_SUBSCRIPTION_DELETE`;
    public readonly APP_PERMIT_SUBSCRIPTION_RECOVERY = `APP_PERMIT_SUBSCRIPTION_RECOVERY`;
    public readonly APP_PERMIT_SUBSCRIPTION_COUNT = `APP_PERMIT_SUBSCRIPTION_COUNT`;

    /**
     * PAYMENT_METHOD PERMIT
     */
    public readonly APP_PERMIT_COIN_LIST = `APP_PERMIT_COIN_LIST`;
    public readonly APP_PERMIT_COIN_CREATE = `APP_PERMIT_COIN_CREATE`;
    public readonly APP_PERMIT_COIN_UPDATE = `APP_PERMIT_COIN_UPDATE`;
    public readonly APP_PERMIT_COIN_DELETE = `APP_PERMIT_COIN_DELETE`;
    public readonly APP_PERMIT_COIN_RECOVERY = `APP_PERMIT_COIN_RECOVERY`;
    public readonly APP_PERMIT_COIN_COUNT = `APP_PERMIT_COIN_COUNT`;


    /**
     * PAYMENT_METHOD PERMIT
     */
    public readonly APP_PERMIT_PAYMENT_METHOD_LIST = `APP_PERMIT_PAYMENT_METHOD_LIST`;
    public readonly APP_PERMIT_PAYMENT_METHOD_CREATE = `APP_PERMIT_PAYMENT_METHOD_CREATE`;
    public readonly APP_PERMIT_PAYMENT_METHOD_UPDATE = `APP_PERMIT_PAYMENT_METHOD_UPDATE`;
    public readonly APP_PERMIT_PAYMENT_METHOD_DELETE = `APP_PERMIT_PAYMENT_METHOD_DELETE`;
    public readonly APP_PERMIT_PAYMENT_METHOD_RECOVERY = `APP_PERMIT_PAYMENT_METHOD_RECOVERY`;
    public readonly APP_PERMIT_PAYMENT_METHOD_COUNT = `APP_PERMIT_PAYMENT_METHOD_COUNT`;

    /**
     * PERMISOS REFERENTE A NUTRICIÓN
     */

    /**
     * ADMIN INICIO
     */

    /**
     * UNITY_MEASURE PERMIT
     */
    public readonly APP_PERMIT_UNITY_MEASURE_LIST = `APP_PERMIT_UNITY_MEASURE_LIST`;
    public readonly APP_PERMIT_UNITY_MEASURE_CREATE = `APP_PERMIT_UNITY_MEASURE_CREATE`;
    public readonly APP_PERMIT_UNITY_MEASURE_UPDATE = `APP_PERMIT_UNITY_MEASURE_UPDATE`;
    public readonly APP_PERMIT_UNITY_MEASURE_DELETE = `APP_PERMIT_UNITY_MEASURE_DELETE`;
    public readonly APP_PERMIT_UNITY_MEASURE_RECOVERY = `APP_PERMIT_UNITY_MEASURE_RECOVERY`;
    public readonly APP_PERMIT_UNITY_MEASURE_COUNT = `APP_PERMIT_UNITY_MEASURE_COUNT`;

    /**
     * SUPPLEMENT PERMIT
     */
    public readonly APP_PERMIT_SUPPLEMENT_LIST = `APP_PERMIT_SUPPLEMENT_LIST`;
    public readonly APP_PERMIT_SUPPLEMENT_CREATE = `APP_PERMIT_SUPPLEMENT_CREATE`;
    public readonly APP_PERMIT_SUPPLEMENT_UPDATE = `APP_PERMIT_SUPPLEMENT_UPDATE`;
    public readonly APP_PERMIT_SUPPLEMENT_DELETE = `APP_PERMIT_SUPPLEMENT_DELETE`;
    public readonly APP_PERMIT_SUPPLEMENT_RECOVERY = `APP_PERMIT_SUPPLEMENT_RECOVERY`;
    public readonly APP_PERMIT_SUPPLEMENT_COUNT = `APP_PERMIT_SUPPLEMENT_COUNT`;

    /**
     * PRESENTATION PERMIT
     */
    public readonly APP_PERMIT_PRESENTATION_LIST = `APP_PERMIT_PRESENTATION_LIST`;
    public readonly APP_PERMIT_PRESENTATION_CREATE = `APP_PERMIT_PRESENTATION_CREATE`;
    public readonly APP_PERMIT_PRESENTATION_UPDATE = `APP_PERMIT_PRESENTATION_UPDATE`;
    public readonly APP_PERMIT_PRESENTATION_DELETE = `APP_PERMIT_PRESENTATION_DELETE`;
    public readonly APP_PERMIT_PRESENTATION_RECOVERY = `APP_PERMIT_PRESENTATION_RECOVERY`;
    public readonly APP_PERMIT_PRESENTATION_COUNT = `APP_PERMIT_PRESENTATION_COUNT`;


    /**
     * ADMIN FIN
     */

    /**
     * FOOD PERMIT
     */
    public readonly APP_PERMIT_FOOD_LIST = `APP_PERMIT_FOOD_LIST`;
    public readonly APP_PERMIT_FOOD_CREATE = `APP_PERMIT_FOOD_CREATE`;
    public readonly APP_PERMIT_FOOD_UPDATE = `APP_PERMIT_FOOD_UPDATE`;
    public readonly APP_PERMIT_FOOD_DELETE = `APP_PERMIT_FOOD_DELETE`;
    public readonly APP_PERMIT_FOOD_RECOVERY = `APP_PERMIT_FOOD_RECOVERY`;
    public readonly APP_PERMIT_FOOD_COUNT = `APP_PERMIT_FOOD_COUNT`;

    /**
     * DIETARY PERMIT
     */
    public readonly APP_PERMIT_DIETARY_LIST = `APP_PERMIT_DIETARY_LIST`;
    public readonly APP_PERMIT_DIETARY_CREATE = `APP_PERMIT_DIETARY_CREATE`;
    public readonly APP_PERMIT_DIETARY_UPDATE = `APP_PERMIT_DIETARY_UPDATE`;
    public readonly APP_PERMIT_DIETARY_DELETE = `APP_PERMIT_DIETARY_DELETE`;
    public readonly APP_PERMIT_DIETARY_RECOVERY = `APP_PERMIT_DIETARY_RECOVERY`;
    public readonly APP_PERMIT_DIETARY_COUNT = `APP_PERMIT_DIETARY_COUNT`;

    /**
     * EXCHANGE_LIST PERMIT
     */
    public readonly APP_PERMIT_EXCHANGE_LIST_LIST = `APP_PERMIT_EXCHANGE_LIST_LIST`;
    public readonly APP_PERMIT_EXCHANGE_LIST_CREATE = `APP_PERMIT_EXCHANGE_LIST_CREATE`;
    public readonly APP_PERMIT_EXCHANGE_LIST_UPDATE = `APP_PERMIT_EXCHANGE_LIST_UPDATE`;
    public readonly APP_PERMIT_EXCHANGE_LIST_DELETE = `APP_PERMIT_EXCHANGE_LIST_DELETE`;
    public readonly APP_PERMIT_EXCHANGE_LIST_RECOVERY = `APP_PERMIT_EXCHANGE_LIST_RECOVERY`;
    public readonly APP_PERMIT_EXCHANGE_LIST_COUNT = `APP_PERMIT_EXCHANGE_LIST_COUNT`;    
    public readonly APP_PERMIT_EXCHANGE_LIST_ADD = `APP_PERMIT_EXCHANGE_LIST_ADD`;

    /**
     * EXCHANGE_LIST PERMIT
     */
    public readonly APP_PERMIT_PROPIETARY_EXCHANGE_LIST_LIST = `APP_PERMIT_PROPIETARY_EXCHANGE_LIST_LIST`;
    public readonly APP_PERMIT_PROPIETARY_EXCHANGE_LIST_CREATE = `APP_PERMIT_PROPIETARY_EXCHANGE_LIST_CREATE`;
    public readonly APP_PERMIT_PROPIETARY_EXCHANGE_LIST_UPDATE = `APP_PERMIT_PROPIETARY_EXCHANGE_LIST_UPDATE`;
    public readonly APP_PERMIT_PROPIETARY_EXCHANGE_LIST_DELETE = `APP_PERMIT_PROPIETARY_EXCHANGE_LIST_DELETE`;
    public readonly APP_PERMIT_PROPIETARY_EXCHANGE_LIST_RECOVERY = `APP_PERMIT_PROPIETARY_EXCHANGE_LIST_RECOVERY`;
    public readonly APP_PERMIT_PROPIETARY_EXCHANGE_LIST_COUNT = `APP_PERMIT_PROPIETARY_EXCHANGE_LIST_COUNT`;    
    public readonly APP_PERMIT_PROPIETARY_EXCHANGE_LIST_ADD = `APP_PERMIT_PROPIETARY_EXCHANGE_LIST_ADD`;


    /**
     * MENU PERMIT
     */
    public readonly APP_PERMIT_MENU_LIST = `APP_PERMIT_MENU_LIST`;
    public readonly APP_PERMIT_MENU_CREATE = `APP_PERMIT_MENU_CREATE`;
    public readonly APP_PERMIT_MENU_UPDATE = `APP_PERMIT_MENU_UPDATE`;
    public readonly APP_PERMIT_MENU_DELETE = `APP_PERMIT_MENU_DELETE`;
    public readonly APP_PERMIT_MENU_RECOVERY = `APP_PERMIT_MENU_RECOVERY`;
    public readonly APP_PERMIT_MENU_COUNT = `APP_PERMIT_MENU_COUNT`;   
    public readonly APP_PERMIT_MENU_ADD = `APP_PERMIT_MENU_ADD`;

    public readonly APP_PERMIT_PROPIETARY_MENU_LIST = `APP_PERMIT_PROPIETARY_MENU_LIST`;
    public readonly APP_PERMIT_PROPIETARY_MENU_CREATE = `APP_PERMIT_PROPIETARY_MENU_CREATE`;
    public readonly APP_PERMIT_PROPIETARY_MENU_UPDATE = `APP_PERMIT_PROPIETARY_MENU_UPDATE`;
    public readonly APP_PERMIT_PROPIETARY_MENU_DELETE = `APP_PERMIT_PROPIETARY_MENU_DELETE`;
    public readonly APP_PERMIT_PROPIETARY_MENU_RECOVERY = `APP_PERMIT_PROPIETARY_MENU_RECOVERY`;
    public readonly APP_PERMIT_PROPIETARY_MENU_COUNT = `APP_PERMIT_PROPIETARY_MENU_COUNT`;   
    public readonly APP_PERMIT_PROPIETARY_MENU_ADD = `APP_PERMIT_PROPIETARY_MENU_ADD`;

    /**
     * QUOTE PERMIT
     */
    public readonly APP_PERMIT_QUOTE_LIST = `APP_PERMIT_QUOTE_LIST`;
    public readonly APP_PERMIT_QUOTE_CREATE = `APP_PERMIT_QUOTE_CREATE`;
    public readonly APP_PERMIT_QUOTE_UPDATE = `APP_PERMIT_QUOTE_UPDATE`;
    public readonly APP_PERMIT_QUOTE_DELETE = `APP_PERMIT_QUOTE_DELETE`;
    public readonly APP_PERMIT_QUOTE_RECOVERY = `APP_PERMIT_QUOTE_RECOVERY`;
    public readonly APP_PERMIT_QUOTE_COUNT = `APP_PERMIT_QUOTE_COUNT`;

    /**
    * QUOTE PERMIT PROPIETARY
    */
    public readonly APP_PERMIT_PROPIETARY_QUOTE_LIST = `APP_PERMIT_PROPIETARY_QUOTE_LIST`;
    public readonly APP_PERMIT_PROPIETARY_QUOTE_CREATE = `APP_PERMIT_PROPIETARY_QUOTE_CREATE`;
    public readonly APP_PERMIT_PROPIETARY_QUOTE_UPDATE = `APP_PERMIT_PROPIETARY_QUOTE_UPDATE`;
    public readonly APP_PERMIT_PROPIETARY_QUOTE_DELETE = `APP_PERMIT_PROPIETARY_QUOTE_DELETE`;
    public readonly APP_PERMIT_PROPIETARY_QUOTE_RECOVERY = `APP_PERMIT_PROPIETARY_QUOTE_RECOVERY`;
    public readonly APP_PERMIT_PROPIETARY_QUOTE_COUNT = `APP_PERMIT_PROPIETARY_QUOTE_COUNT`;

    /**
     * CALENDAT PERMIT
     */
    public readonly APP_PERMIT_CALENDAR_LIST = `APP_PERMIT_CALENDAR_LIST`;
    public readonly APP_PERMIT_CALENDAR_CREATE = `APP_PERMIT_CALENDAR_CREATE`;
    public readonly APP_PERMIT_CALENDAR_UPDATE = `APP_PERMIT_CALENDAR_UPDATE`;
    public readonly APP_PERMIT_CALENDAR_DELETE = `APP_PERMIT_CALENDAR_DELETE`;
    public readonly APP_PERMIT_CALENDAR_RECOVERY = `APP_PERMIT_CALENDAR_RECOVERY`;
    public readonly APP_PERMIT_CALENDAR_COUNT = `APP_PERMIT_CALENDAR_COUNT`;    
    public readonly APP_PERMIT_CALENDAR_ADD = `APP_PERMIT_CALENDAR_ADD`;

    public readonly APP_PERMIT_CALENDAR_PROPIETARY_LIST     = `APP_PERMIT_CALENDAR_PROPIETARY_LIST`;
    public readonly APP_PERMIT_CALENDAR_PROPIETARY_CREATE   = `APP_PERMIT_CALENDAR_PROPIETARY_CREATE`;
    public readonly APP_PERMIT_CALENDAR_PROPIETARY_UPDATE   = `APP_PERMIT_CALENDAR_PROPIETARY_UPDATE`;
    public readonly APP_PERMIT_CALENDAR_PROPIETARY_COUNT    = `APP_PERMIT_CALENDAR_PROPIETARY_COUNT`;    
    public readonly APP_PERMIT_CALENDAR_PROPIETARY_ADD      = `APP_PERMIT_CALENDAR_PROPIETARY_ADD`;



    /**
     * PERMISOS PROPIETARIOS
     */
    public readonly APP_PERMIT_PROPIETARY_QUOTE = `APP_PERMIT_PROPIETARY_QUOTE`;
    public readonly APP_PERMIT_PROPIETARY_PATIENT = `APP_PERMIT_PROPIETARY_PATIENT`;
    public readonly APP_PERMIT_PROPIETARY_NUTRICIONIST = `APP_PERMIT_PROPIETARY_NUTRICIONIST`;

    /**
     * PERMISOS DE APLICACIÓN (ESTADISTICAS, HISTORIAL, REPORTES, GRÁFICOS)
     */
    // PERMISOS AQUÍ


    public readonly USER_SUPER_ADMIN = `USER_SUPER_ADMIN`;
    public readonly USER_APP_ADMIN = `USER_APP_ADMIN`;
    public readonly USER_NUTRI_ADMIN = `USER_NUTRI_ADMIN`;
    public readonly USER_FINANCE = `USER_FINANCE`;

    public readonly USER_NUTRICIONISTA = `USER_NUTRICIONISTA`;
    public readonly USER_PACIENTE = `USER_PACIENTE`;


    public readonly PERMIT_DEFAULT = [
        "APP_PERMIT_PROFILE_SHOW",
        "APP_PERMIT_PROFILE_UPDATE_DATA",
        "APP_PERMIT_PROFILE_UPDATE_PASSWORD",
        "APP_PERMIT_PROFILE_UPDATE_PHOTO",
        "APP_PERMIT_PROFILE_STATICTICS_FOR_MONTH",
        "APP_PERMIT_PROFILE_STATICTICS_FOR_YEAR",
        this.APP_PERMIT_NOTIFICATION_LIST,
        this.APP_PERMIT_NOTIFICATION_CREATE,
        this.APP_PERMIT_NOTIFICATION_UPDATE,
        this.APP_PERMIT_NOTIFICATION_DELETE,
        this.APP_PERMIT_NOTIFICATION_RECOVERY,
        this.APP_PERMIT_NOTIFICATION_COUNT,
    ];

    public readonly CUSTOM_PERMIT_SUPER_ADMIN = [
        ...this.PERMIT_DEFAULT,
        this.APP_PERMIT_USER_LIST,
        this.APP_PERMIT_USER_CREATE,
        this.APP_PERMIT_USER_UPDATE,
        this.APP_PERMIT_USER_DELETE,
        this.APP_PERMIT_USER_RECOVERY,
        this.APP_PERMIT_USER_COUNT,

        this.APP_PERMIT_USER_SPECITY_ADMIN_APP,
        this.APP_PERMIT_USER_SPECITY_NUTRI_APP,
        this.APP_PERMIT_USER_SPECITY_FINANCE,
        this.APP_PERMIT_USER_SPECITY_NUTRICIONISTA,
        this.APP_PERMIT_USER_SPECITY_PACIENTE,

        this.APP_PERMIT_PERMIT_LIST,
        this.APP_PERMIT_PERMIT_CREATE,
        this.APP_PERMIT_PERMIT_UPDATE,
        this.APP_PERMIT_PERMIT_DELETE,
        this.APP_PERMIT_PERMIT_RECOVERY,
        this.APP_PERMIT_PERMIT_COUNT,

        this.APP_PERMIT_COUNTRY_LIST,
        this.APP_PERMIT_COUNTRY_CREATE,
        this.APP_PERMIT_COUNTRY_UPDATE,
        this.APP_PERMIT_COUNTRY_DELETE,
        this.APP_PERMIT_COUNTRY_RECOVERY,
        this.APP_PERMIT_COUNTRY_COUNT,

        this.APP_PERMIT_STATE_LIST,
        this.APP_PERMIT_STATE_CREATE,
        this.APP_PERMIT_STATE_UPDATE,
        this.APP_PERMIT_STATE_DELETE,
        this.APP_PERMIT_STATE_RECOVERY,
        this.APP_PERMIT_STATE_COUNT,

        this.APP_PERMIT_CITY_LIST,
        this.APP_PERMIT_CITY_CREATE,
        this.APP_PERMIT_CITY_UPDATE,
        this.APP_PERMIT_CITY_DELETE,
        this.APP_PERMIT_CITY_RECOVERY,
        this.APP_PERMIT_CITY_COUNT,

        this.APP_PERMIT_SUBSCRIPTION_LIST,
        this.APP_PERMIT_SUBSCRIPTION_CREATE,
        this.APP_PERMIT_SUBSCRIPTION_UPDATE,
        this.APP_PERMIT_SUBSCRIPTION_DELETE,
        this.APP_PERMIT_SUBSCRIPTION_RECOVERY,
        this.APP_PERMIT_SUBSCRIPTION_COUNT,

        this.APP_PERMIT_COIN_LIST,
        this.APP_PERMIT_COIN_CREATE,
        this.APP_PERMIT_COIN_UPDATE,
        this.APP_PERMIT_COIN_DELETE,
        this.APP_PERMIT_COIN_RECOVERY,
        this.APP_PERMIT_COIN_COUNT,

        this.APP_PERMIT_PAYMENT_METHOD_LIST,
        this.APP_PERMIT_PAYMENT_METHOD_CREATE,
        this.APP_PERMIT_PAYMENT_METHOD_UPDATE,
        this.APP_PERMIT_PAYMENT_METHOD_DELETE,
        this.APP_PERMIT_PAYMENT_METHOD_RECOVERY,
        this.APP_PERMIT_PAYMENT_METHOD_COUNT,

        this.APP_PERMIT_UNITY_MEASURE_LIST,
        this.APP_PERMIT_UNITY_MEASURE_CREATE,
        this.APP_PERMIT_UNITY_MEASURE_UPDATE,
        this.APP_PERMIT_UNITY_MEASURE_DELETE,
        this.APP_PERMIT_UNITY_MEASURE_RECOVERY,
        this.APP_PERMIT_UNITY_MEASURE_COUNT,

        this.APP_PERMIT_SUPPLEMENT_LIST,
        this.APP_PERMIT_SUPPLEMENT_CREATE,
        this.APP_PERMIT_SUPPLEMENT_UPDATE,
        this.APP_PERMIT_SUPPLEMENT_DELETE,
        this.APP_PERMIT_SUPPLEMENT_RECOVERY,
        this.APP_PERMIT_SUPPLEMENT_COUNT,

        this.APP_PERMIT_PRESENTATION_LIST,
        this.APP_PERMIT_PRESENTATION_CREATE,
        this.APP_PERMIT_PRESENTATION_UPDATE,
        this.APP_PERMIT_PRESENTATION_DELETE,
        this.APP_PERMIT_PRESENTATION_RECOVERY,
        this.APP_PERMIT_PRESENTATION_COUNT,

        this.APP_PERMIT_FOOD_LIST,
        this.APP_PERMIT_FOOD_CREATE,
        this.APP_PERMIT_FOOD_UPDATE,
        this.APP_PERMIT_FOOD_DELETE,
        this.APP_PERMIT_FOOD_RECOVERY,
        this.APP_PERMIT_FOOD_COUNT,

        this.APP_PERMIT_DIETARY_LIST,
        this.APP_PERMIT_DIETARY_CREATE,
        this.APP_PERMIT_DIETARY_UPDATE,
        this.APP_PERMIT_DIETARY_DELETE,
        this.APP_PERMIT_DIETARY_RECOVERY,
        this.APP_PERMIT_DIETARY_COUNT,

        this.APP_PERMIT_EXCHANGE_LIST_LIST,
        this.APP_PERMIT_EXCHANGE_LIST_CREATE,
        this.APP_PERMIT_EXCHANGE_LIST_UPDATE,
        this.APP_PERMIT_EXCHANGE_LIST_DELETE,
        this.APP_PERMIT_EXCHANGE_LIST_RECOVERY,
        this.APP_PERMIT_EXCHANGE_LIST_COUNT,

        this.APP_PERMIT_MENU_LIST,
        this.APP_PERMIT_MENU_CREATE,
        this.APP_PERMIT_MENU_UPDATE,
        this.APP_PERMIT_MENU_DELETE,
        this.APP_PERMIT_MENU_RECOVERY,
        this.APP_PERMIT_MENU_COUNT,

        this.APP_PERMIT_QUOTE_LIST,
        this.APP_PERMIT_QUOTE_CREATE,
        this.APP_PERMIT_QUOTE_UPDATE,
        this.APP_PERMIT_QUOTE_DELETE,
        this.APP_PERMIT_QUOTE_RECOVERY,
        this.APP_PERMIT_QUOTE_COUNT,

        this.APP_PERMIT_CALENDAR_ADD,
        this.APP_PERMIT_CALENDAR_CREATE,
        this.APP_PERMIT_CALENDAR_COUNT,
        this.APP_PERMIT_CALENDAR_DELETE,
        this.APP_PERMIT_CALENDAR_LIST,
        this.APP_PERMIT_CALENDAR_RECOVERY,
        this.APP_PERMIT_CALENDAR_UPDATE,

        this.APP_PERMIT_CALENDAR_ADD,
        this.APP_PERMIT_CALENDAR_COUNT,
        this.APP_PERMIT_CALENDAR_CREATE,
        this.APP_PERMIT_CALENDAR_LIST,
        this.APP_PERMIT_CALENDAR_UPDATE,
    ];

    public readonly CUSTOM_PERMIT_APP_ADMIN = [
        ...this.PERMIT_DEFAULT,
        this.APP_PERMIT_PERMIT_LIST,
        this.APP_PERMIT_COUNTRY_LIST,
        this.APP_PERMIT_COUNTRY_CREATE,
        this.APP_PERMIT_COUNTRY_UPDATE,
        this.APP_PERMIT_COUNTRY_COUNT,
        this.APP_PERMIT_STATE_LIST,
        this.APP_PERMIT_STATE_CREATE,
        this.APP_PERMIT_STATE_UPDATE,
        this.APP_PERMIT_STATE_COUNT,
        this.APP_PERMIT_CITY_LIST,
        this.APP_PERMIT_CITY_CREATE,
        this.APP_PERMIT_CITY_UPDATE,
        this.APP_PERMIT_CITY_COUNT,
        this.APP_PERMIT_SUBSCRIPTION_LIST,
        this.APP_PERMIT_SUBSCRIPTION_CREATE,
        this.APP_PERMIT_SUBSCRIPTION_UPDATE,
        this.APP_PERMIT_SUBSCRIPTION_COUNT,
        this.APP_PERMIT_COIN_LIST,
        this.APP_PERMIT_COIN_CREATE,
        this.APP_PERMIT_COIN_UPDATE,
        this.APP_PERMIT_COIN_COUNT,
        this.APP_PERMIT_PAYMENT_METHOD_LIST,
        this.APP_PERMIT_PAYMENT_METHOD_CREATE,
        this.APP_PERMIT_PAYMENT_METHOD_UPDATE,
        this.APP_PERMIT_PAYMENT_METHOD_COUNT,

    ];

    public readonly CUSTOM_PERMIT_NUTRI_ADMIN = [
        ...this.PERMIT_DEFAULT,
        this.APP_PERMIT_UNITY_MEASURE_LIST,
        this.APP_PERMIT_UNITY_MEASURE_CREATE,
        this.APP_PERMIT_UNITY_MEASURE_UPDATE,
        this.APP_PERMIT_UNITY_MEASURE_DELETE,
        this.APP_PERMIT_UNITY_MEASURE_RECOVERY,
        this.APP_PERMIT_UNITY_MEASURE_COUNT,

        this.APP_PERMIT_SUPPLEMENT_LIST,
        this.APP_PERMIT_SUPPLEMENT_CREATE,
        this.APP_PERMIT_SUPPLEMENT_UPDATE,
        this.APP_PERMIT_SUPPLEMENT_DELETE,
        this.APP_PERMIT_SUPPLEMENT_RECOVERY,
        this.APP_PERMIT_SUPPLEMENT_COUNT,

        this.APP_PERMIT_PRESENTATION_LIST,
        this.APP_PERMIT_PRESENTATION_CREATE,
        this.APP_PERMIT_PRESENTATION_UPDATE,
        this.APP_PERMIT_PRESENTATION_DELETE,
        this.APP_PERMIT_PRESENTATION_RECOVERY,
        this.APP_PERMIT_PRESENTATION_COUNT,

        this.APP_PERMIT_FOOD_LIST,
        this.APP_PERMIT_FOOD_CREATE,
        this.APP_PERMIT_FOOD_UPDATE,
        this.APP_PERMIT_FOOD_DELETE,
        this.APP_PERMIT_FOOD_RECOVERY,
        this.APP_PERMIT_FOOD_COUNT,

        this.APP_PERMIT_DIETARY_LIST,
        this.APP_PERMIT_DIETARY_CREATE,
        this.APP_PERMIT_DIETARY_UPDATE,
        this.APP_PERMIT_DIETARY_DELETE,
        this.APP_PERMIT_DIETARY_RECOVERY,
        this.APP_PERMIT_DIETARY_COUNT,

        this.APP_PERMIT_EXCHANGE_LIST_LIST,
        this.APP_PERMIT_EXCHANGE_LIST_CREATE,
        this.APP_PERMIT_EXCHANGE_LIST_UPDATE,
        this.APP_PERMIT_EXCHANGE_LIST_DELETE,
        this.APP_PERMIT_EXCHANGE_LIST_RECOVERY,
        this.APP_PERMIT_EXCHANGE_LIST_COUNT,

        this.APP_PERMIT_MENU_LIST,
        this.APP_PERMIT_MENU_CREATE,
        this.APP_PERMIT_MENU_UPDATE,
        this.APP_PERMIT_MENU_DELETE,
        this.APP_PERMIT_MENU_RECOVERY,
        this.APP_PERMIT_MENU_COUNT,

        this.APP_PERMIT_QUOTE_LIST,
        this.APP_PERMIT_QUOTE_CREATE,
        this.APP_PERMIT_QUOTE_UPDATE,
        this.APP_PERMIT_QUOTE_DELETE,
        this.APP_PERMIT_QUOTE_RECOVERY,
        this.APP_PERMIT_QUOTE_COUNT,
    ];

    public readonly CUSTOM_PERMIT_NUTRICIONISTA = [
        ...this.PERMIT_DEFAULT,
        this.APP_PERMIT_PROPIETARY_QUOTE,
        this.APP_PERMIT_PROPIETARY_QUOTE_LIST,
        this.APP_PERMIT_PROPIETARY_QUOTE_CREATE,
        this.APP_PERMIT_PROPIETARY_QUOTE_UPDATE,
        this.APP_PERMIT_PROPIETARY_QUOTE_RECOVERY,
        this.APP_PERMIT_PROPIETARY_QUOTE_COUNT,

        this.APP_PERMIT_PROPIETARY_EXCHANGE_LIST_LIST,
        this.APP_PERMIT_PROPIETARY_EXCHANGE_LIST_CREATE,
        this.APP_PERMIT_PROPIETARY_EXCHANGE_LIST_UPDATE,
        this.APP_PERMIT_PROPIETARY_EXCHANGE_LIST_DELETE,
        this.APP_PERMIT_PROPIETARY_EXCHANGE_LIST_RECOVERY,
        this.APP_PERMIT_PROPIETARY_EXCHANGE_LIST_COUNT,

        this.APP_PERMIT_PROPIETARY_MENU_LIST,
        this.APP_PERMIT_PROPIETARY_MENU_CREATE,
        this.APP_PERMIT_PROPIETARY_MENU_UPDATE,
        this.APP_PERMIT_PROPIETARY_MENU_DELETE,
        this.APP_PERMIT_PROPIETARY_MENU_RECOVERY,
        this.APP_PERMIT_PROPIETARY_MENU_COUNT,

        this.APP_PERMIT_CALENDAR_PROPIETARY_ADD,
        this.APP_PERMIT_CALENDAR_PROPIETARY_COUNT,
        this.APP_PERMIT_CALENDAR_PROPIETARY_CREATE,
        this.APP_PERMIT_CALENDAR_PROPIETARY_LIST,
        this.APP_PERMIT_CALENDAR_PROPIETARY_UPDATE,

        this.APP_PERMIT_PROPIETARY_PATIENT,

        this.APP_PERMIT_USER_SPECITY_PACIENTE,

        this.APP_PERMIT_FOOD_LIST,
        this.APP_PERMIT_FOOD_CREATE,
        this.APP_PERMIT_FOOD_COUNT,

    ];

    public readonly CUSTOM_PERMIT_PACIENTE = [
        ...this.PERMIT_DEFAULT,
        this.APP_PERMIT_PROPIETARY_QUOTE_LIST,
        this.APP_PERMIT_PROPIETARY_QUOTE_COUNT,
        this.APP_PERMIT_PROPIETARY_MENU_LIST,
        this.APP_PERMIT_PROPIETARY_MENU_COUNT,

        this.APP_PERMIT_CALENDAR_PROPIETARY_COUNT,
        this.APP_PERMIT_CALENDAR_PROPIETARY_LIST,
    ];

    public readonly CUSTOM_PERMIT_FINANCE = [
        ...this.PERMIT_DEFAULT,
    ]

    public readonly PERMIT_FINANCE = [
        ...this.PERMIT_DEFAULT,
    ];

} 
